### ISSUE TITLE
Change file date to new file once an updated date larger than a certain amount takes place after startup.

### ISSUE THREAD

**Issue by sprinkjm** [jmscslgroup/libpanda#11]
* @blegas78

**Comment by sprinkjm** [comment]
This may be in-progress, or may be done. @blegas78 can you update?

**Comment by blegas78** [comment]
Vehicle_interface.cpp has already been updated to start CSV files and after system time has been set from GPS time.  I feel this will be sufficient.  CSV uploads from testing in our most recent testing day should indicate success
