### ISSUE TITLE
"Controls enabled" topics for safety/supervisory interaction.

### ISSUE THREAD

**Issue by sprinkjm** [jmscslgroup/libpanda#18]
Let's say there is a topic /car/panda/controls_enabled, which indicates that control is now coming from ROS (or other) libpanda components.

Need a new logic where this is more of a handshake, if (and only if) a handshake component is running. If no handshake component is running, then we would explicitly map controls requested directly to a topic that enabled controls (or we would have a way to bypass as a config option or command-line switch to change from the default mode).

Here is the current use case:
* Driver turns on radar
* Driver presses "set" to enable controls
* Driver presses "resume" and vehicle executes commands

When testing in traffic, however, the following use case is used:
* Driver turns on radar
* Safety team member watches for current acceleration commands, and to determine whether controller is in an appropriate state
* Safety team member gives 'go ahead' for driver
* Driver presses "Set" and then "Resume"

The desired use case is:
* Driver turns on radar
* Driver presses "Set", requesting controls
** If commands do not make sense, safety/sanity node rejects request for controls and chimes, with "Cruise Control Unavailable" (or similar) HUD msg
** If commands *do* make sense, safety/sanity node notifies libpanda that controls should be enabled
** libpanda then publishes controls_enabled topic

**Comment by sprinkjm** [comment]
Couple things to also resolve:
* is my understanding correct above?
* do drivers still have to press 'res' to get vehicle moving?
* what topics would we need to add, if we wanted to enable this for 8/2/21 testing?

**Comment by blegas78** [comment]
1) The logic in general makes sense to me.  We need to define what the "appropriate state" would be, I assume that it's the /cmd_accel being within certain bounds and maybe also the radar.  My one concern is that if we keep cancelling cruise, there is no indication to the driving team why we keep cancelling.

2) I am unsure of the few possible ways to re-engage cruise on default cars but I believe pressing resume alone is sufficient.  We are not currently reading the set/resume button, instead we are reading the car's built-in cruise state which is produced from those button presses.  I feel that this same method will be sufficient and we will not need to read exact set/resume button presses.  If we detect a rising edge on /car/libpanda/controlls_allowed and our "appropriate state" does not pass, then the cancel request can be invoked and no controls can be sent nearly immediately

3) I don't think any new topics are needed, just a new ROS node akin to the simple_mini_car_from_yes_this_name_is_too_long_lead_distance.cpp node in can_to_ros

**Comment by sprinkjm** [comment]
For (1) I also agree, we have to ensure we aren't too conservative here. I am thjnking if lead car exists, and commanded accel is less than +/- 0.5, them we should enable. We can still have a safety person monitor a topic for this week to help in engaging

**Comment by sprinkjm** [comment]
if you can draft up that new node this morning, perhaps we can integrate mid-afternoon. I'll handle the nity node when I get in, will just be watching for rising edge of your topic, and checking the other jnputs before publishing on the new topic you suggest that it is ok to go.

**Comment by blegas78** [comment]
libpanda and can_to_ros hv been updated with the node cruise_start_safety_check.cpp.  Lightly verified with manually "rostopic pub ..." to be working while at standstill
